name: setting
description: A professional app for your settings.

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Dart SDK version constraints
environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # Preferences & dotenv
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0

  # Local authentication
  local_auth: ^2.1.7

  # Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Icon generator (was missing in your original version)
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/settings.png"
